"""empty message

Revision ID: c13d593a732a
Revises: None
Create Date: 2016-09-08 16:16:01.917300

"""

# revision identifiers, used by Alembic.
revision = 'c13d593a732a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hours')
    ### end Alembic commands ###
