"""empty message

Revision ID: c5e4788def3d
Revises: None
Create Date: 2016-09-09 11:11:59.114392

"""

# revision identifiers, used by Alembic.
revision = 'c5e4788def3d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'admin', 'desc', 'date', 'item')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hours')
    ### end Alembic commands ###
